const ActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  FETCH_CATALOG: 'FETCH_CATALOG',
  RECEIVE_CATALOG: 'RECEIVE_CATALOG',
  FETCH_ARTICLE: 'FETCH_ARTICLE'
}

export default ActionTypes;
